"""Write reports/DERIVED_LICENCE_AUDIT.md: every tracked file derived from a release, with that release's terms.

What it does: lists the tracked notebooks, previews, tables and data extracts (from ``git ls-files``) that are
derived from one or more releases, finds which releases each one comes from, and prints the registry's
derived-output note for each (fielddata/registry.py, ``derived_outputs``). A file made from several releases
lists every note.

Decision recorded here (Robert, 2 October 2026): this repository is non-commercial (free, public, academic, no
revenue). Derived outputs of the four non-commercial releases are published under each release's own license.
Previews and facts of the two releases that state no data license (ppl, zhou2026) are also published; their
authors were asked and did not reply.

Reads: git's list of tracked files and fielddata/registry.py. It does not open any released data.
Writes: reports/DERIVED_LICENCE_AUDIT.md. Rerun: python scripts/license_audit.py
"""
from __future__ import annotations

import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from fielddata.registry import PACKAGES  # noqa: E402

OUT = ROOT / "reports" / "DERIVED_LICENCE_AUDIT.md"
SCANNED = ("notebooks/", "reports/", "docs/dashboard/")
KINDS = (".ipynb", ".csv", ".json", ".png", ".txt")
# Files whose name does not say which release they come from.
NAMED = {
    "notebooks/quickstart.ipynb": ["tsukuba"],  # its saved run uses tsukuba
}
ALL = sorted(PACKAGES)
EVERY_RELEASE = {"docs/dashboard/index.html", "docs/dashboard/status.json", "reports/TOTALS.md", "reports/totals.json",
                 "reports/TABLE1_access.md", "reports/verify_log.csv", "reports/verify_log_ssd_2026-09.csv"}


def tracked() -> list[str]:
    out = subprocess.run(["git", "ls-files", *SCANNED], cwd=ROOT, capture_output=True, text=True, check=True).stdout
    return sorted(line for line in out.splitlines() if line)


def releases(path: str) -> list[str]:
    if path in NAMED:
        return NAMED[path]
    if path in EVERY_RELEASE:
        return ALL
    name = Path(path).name.lower()
    found = [p for p in ALL if p in name or p.replace("-", "_") in name]
    # a longer name wins over a shorter one it contains (m5bat-pbacid, not m5bat)
    return sorted(p for p in found if not any(q != p and p in q and q in found for q in found))


def main() -> None:
    rows = []
    for path in tracked():
        if not (path.endswith(KINDS) or path in EVERY_RELEASE):
            continue
        packages = releases(path)
        if not packages:
            continue
        notes = sorted({PACKAGES[p]["derived_outputs"] for p in packages})
        rows.append((path, packages, notes))
    counts = Counter(note for _, packages, _ in rows for note in {PACKAGES[p]["derived_outputs"] for p in packages})
    lines = [
        "# Derived-output license audit",
        "",
        "Generated by `python scripts/license_audit.py`. It lists every tracked file in this repository that is derived from one or more releases, with each release's derived-output note from `fielddata/registry.py`.",
        "",
        "Decision (Robert, 2 October 2026): this repository is non-commercial use (free, public, academic, no revenue).",
        "",
        "- Releases under CC BY, CC0 or MIT: derived outputs may be published, crediting the release.",
        "- The four non-commercial releases (changan and evbattery, CC BY-NC-SA 4.0; schaeffer and tumftm, CC BY-NC 4.0): derived outputs are published for non-commercial use only, each under its release's license. The dashboard prints that license under each preview.",
        "- The two releases with no stated data license (ppl, zhou2026): previews and facts are published by maintainer decision. Their authors were emailed and did not reply. The dashboard says under each preview that no license is stated.",
        "",
        f"{len(rows)} tracked files are derived from releases. Files per note (a file made from several releases counts under each): "
        + "; ".join(f"{note}: {n}" for note, n in sorted(counts.items())) + ".",
        "",
        "| Tracked file | Release(s) | Derived-output note(s) |",
        "|---|---|---|",
    ]
    for path, packages, notes in rows:
        shown = f"all {len(ALL)} releases" if packages == ALL else ", ".join(packages)
        lines.append(f"| `{path}` | {shown} | {'; '.join(notes)} |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} files")


if __name__ == "__main__":
    main()
