"""Build the public access table from registry metadata and the saved verification log."""
from __future__ import annotations

import csv
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from fielddata.registry import PACKAGES

VERIFY = ROOT / "reports" / "verify_log_ssd_2026-09.csv"
OUTPUT = ROOT / "reports" / "TABLE1_access.md"


def source_commit() -> str:
    paths = [
        "fielddata/registry.py",
        "scripts/table1.py",
        "scripts/rebuild.py",
        "reports/verify_log_ssd_2026-09.csv",
    ]
    result = subprocess.run(
        ["git", "log", "-1", "--format=%H", "--", *paths],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def provenance() -> str:
    if OUTPUT.is_file():
        for line in OUTPUT.read_text(encoding="utf-8").splitlines():
            if line.startswith("Generated by `scripts/rebuild.py`"):
                return line
    return f"Generated by `scripts/rebuild.py` | source commit `{source_commit()}` | date {date.today().isoformat()}"


def read_verify() -> list[dict[str, str]]:
    with VERIFY.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def paper_link(value: str | None) -> str:
    if value and value.startswith("https://doi.org/"):
        return f"[paper]({value})"
    return "—"


def link(label: str, value: str | None) -> str:
    return f"[{label}]({value})" if value else "—"


def checksum_summary(statuses: Counter[str]) -> str:
    parts = []
    if statuses["match"]:
        parts.append(f"{statuses['match']} publisher match")
    if statuses["own hash, no publisher reference"]:
        parts.append(f"{statuses['own hash, no publisher reference']} own hash")
    unexpected = sum(count for status, count in statuses.items() if status not in {"match", "own hash, no publisher reference"})
    if unexpected:
        parts.append(f"{unexpected} other")
    return "; ".join(parts) or "not held"


def build() -> str:
    rows = read_verify()
    files: dict[str, int] = defaultdict(int)
    sizes: dict[str, int] = defaultdict(int)
    statuses: dict[str, Counter[str]] = defaultdict(Counter)
    for row in rows:
        if " :: " in row["file"] or row["file"] == "<package>" or row["status"].lower().startswith("missing"):
            continue
        package = row["package"]
        files[package] += 1
        sizes[package] += int(row["bytes"])
        statuses[package][row["status"]] += 1

    lines = [
        "# Table 1: package access",
        "",
        provenance(),
        "",
        "Size held is decimal GB. File and checksum counts describe physical held files; archive-member verification rows are excluded.",
        "",
        "| Package | Paper DOI | Data record | Code | License | Derived outputs | Size held (GB) | Files | Checksum status |",
        "|---|---|---|---|---|---|---:|---:|---|",
    ]
    for package, meta in PACKAGES.items():
        urls = meta["urls"]
        lines.append(
            "| " + " | ".join([
                package,
                paper_link(urls.get("paper")),
                link("data", urls.get("data")),
                link("code", urls.get("code")),
                f"[{meta['license']}]({meta['license_source']})",
                meta["derived_outputs"],
                f"{sizes[package] / 1_000_000_000:.3f}",
                str(files[package]),
                checksum_summary(statuses[package]),
            ]) + " |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUTPUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
