"""Build Table 2 (package overview) and Table 4 (release versus paper) from committed facts.

Inputs: fielddata/package_facts.csv, fielddata/registry.py, docs/descriptor/paper_claims.csv.
Outputs: docs/descriptor/TABLE2_packages.md, docs/descriptor/TABLE4_release_vs_paper.md.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from fielddata.registry import PACKAGES  # noqa: E402

FACTS = ROOT / "fielddata" / "package_facts.csv"
CLAIMS = ROOT / "docs" / "descriptor" / "paper_claims.csv"
TABLE2 = ROOT / "docs" / "descriptor" / "TABLE2_packages.md"
TABLE4 = ROOT / "docs" / "descriptor" / "TABLE4_release_vs_paper.md"
TABLE4_DIFF = ROOT / "docs" / "descriptor" / "TABLE4_differences.md"
SPAN_TOLERANCE = 0.02  # relative; counts must match exactly

LABELS = {
    "units_released": "units",
    "cells_liion": "Li-ion cells",
    "cells_leadacid": "lead-acid cells",
    "cell_channels_measured": "cell channels",
    "energy_mwh": "MWh",
    "span_unit_years": "unit-years",
}


# Chemistry as shown in Table 2: one short vocabulary; the full value and how it was established stay in
# fielddata/package_facts.csv.
_CHEM_TOKENS = [
    (r"NMC-class", "NMC-class"), (r"(?<!LMO/)\bNMC\b(?!-class)|\bNCM\b", "NMC"), (r"\bNCA\b", "NCA"), (r"\bLFP\b", "LFP"),
    (r"\bLMO/NMC\b", "LMO/NMC"), (r"\bLMO\b(?!/NMC)", "LMO"),
    (r"\bLTO\b", "LTO"), (r"lead-acid|\bOCSM\b|\bOPzV\b", "lead-acid"), (r"lithium-ion|Li-ion|Li-poly", "Li-ion"),
]


def chemistry_label(value: str) -> str:
    import re
    if not value:
        return "not stated"
    found = []
    for pattern, label in _CHEM_TOKENS:
        for match in re.finditer(pattern, value):
            found.append((match.start(), label))
    labels = []
    for _, label in sorted(found):
        if label not in labels and not (label == "NMC" and "NMC-class" in labels) and not (label == "NMC-class" and "NMC" in labels):
            labels.append(label)
    if len(labels) > 1 and "Li-ion" in labels:
        labels.remove("Li-ion")
    return ", ".join(labels) or "not stated"


def load_facts() -> dict[str, dict[str, dict[str, str]]]:
    facts: dict[str, dict[str, dict[str, str]]] = {}
    with FACTS.open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            facts.setdefault(row["package"], {})[row["field"]] = row
    return facts


def num(text: str) -> float | None:
    try:
        return float(text)
    except (TypeError, ValueError):
        return None


def fmt(value: float | None, field: str) -> str:
    if value is None:
        return "not in release"
    if field in ("span_unit_years",):
        return f"{value:,.1f}"
    if field == "energy_mwh":
        return f"{value:,.3f}".rstrip("0").rstrip(".")
    if field in ("obs_hours",):
        return f"{value:,.0f}"
    if field == "size_gb":
        return f"{value:,.2f}" if value >= 0.01 else "<0.01"
    return f"{value:,.0f}" if abs(value - round(value)) < 1e-9 else f"{value:,.3f}"


# Country of the batteries, from each paper or data record (cloverleaf: Circusol demonstrator in Belgium; fei_bus: not stated).
COUNTRY = {
    "tsukuba": "Japan", "cloverleaf": "Belgium", "evbattery": "China", "deng": "China",
    "flashbattery-agv": "Italy", "zhang2023": "China", "bilfinger2024": "Germany", "fei_bus": "not stated",
    "m5bat-2023-04": "Germany", "rwth-home": "Germany", "schaeffer": "not stated", "cao": "China",
    "changan": "China", "ku_leuven_bev": "Belgium", "rwth-android": "Germany", "tumftm": "Germany",
    "bilfinger2026": "Germany", "li2026": "not stated", "m5bat-pbacid": "Germany", "ppl": "United States",
    "xie": "not stated", "zhou2026": "China", "aitio": "sub-Saharan Africa",
}
# Paper-versus-release differences shown in Table 2 (agreed 2026-10-01); the full comparison is Table 4 in the repo.
# Maps (package, Table 2 field) to the paper_claims.csv field that holds the paper's figure.
PAPER_IN_TABLE2 = {("li2026", "cells_liion"): "cell_channels_measured", ("xie", "cells_liion"): "cells_liion"}


def table2(facts) -> str:
    lines = [
        "# Table 2. Package overview",
        "",
        "Generated by `scripts/tables.py` from `fielddata/package_facts.csv` and `fielddata/registry.py`; do not edit by hand. "
        "Each value's basis (measured, stated, derived, not in release) and source are in the facts table. "
        "Service time is unit-years where the release has timestamps (calendar dates, except changan, whose timestamps the publisher made relative, so its span is time elapsed, not a calendar period), "
        "otherwise a lower bound on observation-hours (h). "
        "Energy basis: stated means a rating from the paper or record; computed means from stated configuration or from the released data. "
        "Chemistry: NMC-class is inferred from cell voltage (NMC, NCA and LMO cannot be told apart this way); Li-ion means the cathode chemistry is not stated; "
        "lead-acid includes flooded, gel and valve-regulated designs. How each value was established is in the facts table.",
        "",
        "Where a release's unit or cell count differs from its paper, the release value is shown with the paper's in brackets.",
        "",
        "| Package | Service class | Country | Chemistry | Units | Cells | Service time | Energy, MWh (basis) | Size, GB |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    claims = {(c["package"], c["field"]): c for c in csv.DictReader(CLAIMS.open(encoding="utf-8", newline=""))}

    def paper_note(package, field):
        if (package, field) not in PAPER_IN_TABLE2:
            return ""
        claim = claims[(package, PAPER_IN_TABLE2[(package, field)])]
        return f" (paper: {fmt(float(claim['paper_value']), field)})"

    for package in release_order(facts):
        f = facts[package]
        v = {k: num(f[k]["value"]) if k in f else None for k in f}
        cells = []
        if v.get("cells_liion") is not None:
            cells.append(f"{fmt(v['cells_liion'], 'cells_liion')} Li-ion{paper_note(package, 'cells_liion')}")
        if v.get("cells_leadacid") is not None:
            cells.append(f"{fmt(v['cells_leadacid'], 'cells_leadacid')} lead-acid")
        if v.get("span_unit_years") is not None:
            service = f"{fmt(v['span_unit_years'], 'span_unit_years')} unit-years"
        elif v.get("obs_hours") is not None:
            prefix = "" if f["obs_hours"]["basis"] == "stated" else "at least "
            service = f"{prefix}{fmt(v['obs_hours'], 'obs_hours')} h"
        else:
            service = "no timestamps"
        energy = "not available"
        if v.get("energy_mwh") is not None:
            energy = f"{fmt(v['energy_mwh'], 'energy_mwh')} ({f['energy_basis']['value']})"
        chemistry = chemistry_label(f["chemistry"]["value"])
        lines.append(
            f"| {package} | {f['application']['value']} | {COUNTRY[package]} | {chemistry} | "
            f"{fmt(v['units_released'], 'units_released')}{paper_note(package, 'units_released')} | "
            f"{'; '.join(cells) or 'not in release'} | {service} | {energy} | {fmt(v['size_gb'], 'size_gb')} |"
        )
    lines += ["", "Totals, with shared units counted once, are in `reports/TOTALS.md`.", ""]
    return "\n".join(lines)


def compare(paper: float, release: float | None, field: str) -> str:
    if release is None:
        return "not in release"
    if field == "span_unit_years":
        return "match" if abs(release - paper) <= SPAN_TOLERANCE * paper else "differs"
    return "match" if abs(release - paper) < 1e-9 else "differs"


def table4(facts) -> str:
    with CLAIMS.open(encoding="utf-8", newline="") as handle:
        claims = list(csv.DictReader(handle))
    rank = {p: i for i, p in enumerate(release_order({c["package"] for c in claims}))}
    claims.sort(key=lambda c: rank[c["package"]])  # stable: keeps claim order within a release
    lines = [
        "# Table 4. Paper or record versus released holdings",
        "",
        "Generated by `scripts/tables.py` from `docs/descriptor/paper_claims.csv` (what the paper states, with DOI and page) "
        "and `fielddata/package_facts.csv` (what the release holds); do not edit by hand. Where both exist, the release value is used in every total. "
        "Counts must agree exactly; unit-years within 2 percent. A release value whose basis is `stated` comes from the paper itself, so its match is not an independent check.",
        "",
        "| Package | Quantity | Paper or record | Release (basis) | Result | Source | Note |",
        "|---|---|---|---|---|---|---|",
    ]
    counts = {"match": 0, "differs": 0, "not in release": 0}
    for c in claims:
        row = facts[c["package"]][c["field"]]
        paper = float(c["paper_value"])
        release = num(row["value"])
        result = compare(paper, release, c["field"])
        counts[result] += 1
        basis = f" ({row['basis']})" if release is not None else ""
        lines.append(
            f"| {c['package']} | {LABELS.get(c['field'], c['field'])} | {fmt(paper, c['field'])}: {c['statement']} | "
            f"{fmt(release, c['field'])}{basis} | {result} | [{c['source'].replace('https://', '')}]({c['source']}), {c['locator']} | {c['qualification']} |"
        )
    covered = {c["package"] for c in claims}
    missing = sorted(set(facts) - covered)
    lines += [
        "",
        f"Summary: {len(claims)} comparisons over {len(covered)} packages; {counts['match']} match, {counts['differs']} differ, "
        f"{counts['not in release']} not in release. "
        + (f"No paper count to compare for: {', '.join(missing)} (data record only)." if missing else ""),
        "",
    ]
    return "\n".join(lines)


def table4_differences(facts) -> str:
    """Descriptor version of Table 4: only the comparisons that do not match."""
    with CLAIMS.open(encoding="utf-8", newline="") as handle:
        claims = list(csv.DictReader(handle))
    rank = {p: i for i, p in enumerate(release_order({c["package"] for c in claims}))}
    claims.sort(key=lambda c: rank[c["package"]])
    rows, matched = [], 0
    for c in claims:
        row = facts[c["package"]][c["field"]]
        paper = float(c["paper_value"])
        release = num(row["value"])
        if compare(paper, release, c["field"]) == "match":
            matched += 1
            continue
        rows.append(
            f"| {c['package']} | {LABELS.get(c['field'], c['field'])} | {c['statement']} | {fmt(release, c['field'])} | "
            f"[{c['source'].replace('https://doi.org/', 'doi:').replace('https://arxiv.org/abs/', 'arXiv:')}]({c['source']}), {c['locator']} | {c['qualification']} |"
        )
    covered = {c["package"] for c in claims}
    return "\n".join([
        "# Table 4. Where a release differs from its paper or data record",
        "",
        f"Generated by `scripts/tables.py` from the same inputs as `TABLE4_release_vs_paper.md`, which has all {len(claims)} comparisons; do not edit by hand. "
        f"Of {len(claims)} comparisons over {len(covered)} releases, {matched} agree and the {len(rows)} below do not. "
        "Counts must agree exactly; unit-years within 2 percent. Where they differ, the release value is used in every total.",
        "",
        "| Package Name | Quantity | Paper or record | Release | Source | Note |",
        "|---|---|---|---|---|---|",
        *rows,
        "",
    ])


TABLE1 = ROOT / "docs" / "descriptor" / "TABLE1_sources.md"
CITATIONS = ROOT / "docs" / "descriptor" / "citations.csv"
YEARS = ROOT / "docs" / "descriptor" / "figure1_releases.csv"


def release_order(packages):
    """Shared row order for Tables 1 and 2: the year the release first appeared (first online date of the paper, or of
    the data record where there is no paper), then release name."""
    years = {r["package"]: int(r["year"]) for r in csv.DictReader(YEARS.open(encoding="utf-8"))}
    return sorted(packages, key=lambda p: (years[p], p))
# Code shipped inside the data deposit rather than at a separate address.
CODE_IN_DEPOSIT = {"tsukuba": "in deposit"}
# References that are not journal papers with a first author.
OTHER_REFERENCES = {
    "m5bat-2023-04": ("Evaluation operation report, RWTH Publications", "https://doi.org/10.18154/RWTH-2024-04895"),
    "cloverleaf": ("data record only", None),
    "fei_bus": ("data record only", None),
}
_HOSTS = [("zenodo", "Zenodo"), ("figshare", "figshare"), ("10.5287/bodleian", "Oxford ORA"), ("ora.ox.ac.uk", "Oxford ORA"), ("10.6084", "figshare"), ("mediatum", "mediaTUM"),
          ("github", "GitHub"), ("changan", "Changan portal"), ("10.17632", "Mendeley Data"), ("mendeley", "Mendeley Data"),
          ("10.48804", "KU Leuven RDR"), ("publications.rwth", "RWTH Publications"),
          ("1drv.ms", "OneDrive")]


def host(url):
    for key, name in _HOSTS:
        if url and key in url.lower():
            return name
    return "link"


def table1() -> str:
    cites = {r["package"]: r for r in csv.DictReader(CITATIONS.open(encoding="utf-8"))}
    years = {r["package"]: int(r["year"]) for r in csv.DictReader(YEARS.open(encoding="utf-8"))}
    lines = [
        "# Table 1. Sources of the releases",
        "",
        "Generated by `scripts/tables.py` from `fielddata/registry.py`, `docs/descriptor/citations.csv` and "
        "`docs/descriptor/figure1_releases.csv`; do not edit by hand. Sorted by the year each release first appeared (first online date of the paper, or data record "
        "where there is no paper). Links name the host. Licenses marked * restrict commercial use; ** state no license.",
        "",
        "| Year | Reference | Release | Data | Code | License |",
        "|---|---|---|---|---|---|",
    ]
    for package in release_order(PACKAGES):
        urls = PACKAGES[package]["urls"]
        if package in cites:
            c = cites[package]
            authors = c["first_author"] + (" et al." if c["et_al"] == "yes" else (" " if c["et_al"].startswith("and ") else ", ") + c["et_al"])
            reference = f"[{authors}, {c['venue']}]({c['doi_or_url']})"
        else:
            text, link = OTHER_REFERENCES[package]
            reference = f"[{text}]({link})" if link else text
        data = f"[{host(urls.get('data'))}]({urls['data']})"
        code = CODE_IN_DEPOSIT.get(package) or (f"[{host(urls.get('code'))}]({urls['code']})" if urls.get("code") else "none")
        lic = PACKAGES[package].get("license", "unstated")
        mark = " **" if lic.startswith("unstated") else (" *" if "NC" in lic else "")
        lines.append(f"| {years[package]} | {reference} | {package} | {data} | {code} | {lic}{mark} |")
    lines += ["", f"{len(PACKAGES)} releases.", "", download_routes(), ""]
    return "\n".join(lines)


def download_routes() -> str:
    """One sentence on how each release downloads, from fielddata.fetch.route (dated)."""
    from fielddata import fetch
    groups: dict[str, list[str]] = {}
    for package in release_order(PACKAGES):
        groups.setdefault(fetch.route(package), []).append(package)
    parts = [f"one command (`python -m fielddata.fetch <release>`) for {', '.join(groups['one command'])}",
             f"manual in a web browser for {', '.join(groups['manual (browser)'])}"]
    partly = ", ".join(groups.get("partly manual", []))
    sentence = f"Download, as of {fetch.ROUTE_DATE}: " + "; ".join(parts)
    if partly:
        sentence += (f"; partly manual for {partly}, where the command gets the files on GitHub (0.95 GB) and the "
                     "cell-level data (66.6 GB) is on a Box share linked from the repository's `Cell_Level_Data` file, "
                     "which the loader does not read")
    return sentence + "."


def main() -> None:
    facts = load_facts()
    TABLE2.write_text(table2(facts), encoding="utf-8")
    TABLE4.write_text(table4(facts), encoding="utf-8")
    TABLE4_DIFF.write_text(table4_differences(facts), encoding="utf-8")
    TABLE1.write_text(table1(), encoding="utf-8")
    print(f"wrote {TABLE2.relative_to(ROOT)} and {TABLE4.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
